name: Build and push release image
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and push image
      uses: whoan/docker-build-with-cache-action@v1
      with:
        image_name: stiviik/altv/release
        username: ${{ secrets.GPR_USERNAME }}
        password: "${{ secrets.GPR_TOKEN }}"
        registry: docker.pkg.github.com
        dockerfile: release/Dockerfile